name: manual build tachybase

on:
  workflow_dispatch:
    inputs:
      docker_tag:
        description: 'The Docker tag to publish (e.g., "1.0.0", "latest")'
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.18.0
          cache: 'pnpm'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract and format tag name
        id: extract_tag
        run: echo version=`echo "${{ github.ref }}"
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/tachybase/Dockerfile
          push: true
          build-args: |
            TACHYBASE_VERSION=${{ github.event.inputs.docker_tag }}
          tags: |
            ${{ vars.DOCKERHUB_URL }}/tachybase/tachybase:${{ github.event.inputs.docker_tag }}
            ${{ vars.DOCKERHUB_URL }}/tachybase/tachybase:latest
